delete from account;
delete from brand;
delete from client;
delete from currency;
delete from order_record;
delete from purchase;
delete from status;
delete from stock;
ALTER TABLE account AUTO_INCREMENT = 1;
ALTER TABLE brand AUTO_INCREMENT = 1;
ALTER TABLE client AUTO_INCREMENT = 1;
ALTER TABLE currency AUTO_INCREMENT = 1;
ALTER TABLE order_record AUTO_INCREMENT = 1;
ALTER TABLE purchase AUTO_INCREMENT = 1;
ALTER TABLE status AUTO_INCREMENT = 1;
ALTER TABLE stock AUTO_INCREMENT = 1;